use_frameworks!

target 'DelegateCenter_Example' do
  pod 'DelegateCenter', :path => '../'
  pod 'SnapKit', -> ''
  
#  target 'DelegateCenter_Tests' do
#    inherit! :search_paths
#
#    
#  end
end
